# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod" 
    directory: "/app" 
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 10 
    groups:
      tools:
        patterns:
          - "golang.org/x/vuln"
          - "honnef.co/go/tools/*"
          - "github.com/a-h/templ/*"
          - "github.com/air-verse/air"
          - "github.com/pressly/goose/v3"
          - "github.com/sqlc-dev/sqlc"
          - "github.com/swaggo/swag"
          - "github.com/securego/gosec/*"
      golang-x:
        patterns:
          - "golang.org/x/*" 
      dependencies:
        patterns:
          - "*"  