// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// SettingsPage renders the user account settings page
func SettingsPage(environment string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = Navigation(environment).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, " <div class=\"page-container\"><h1 class=\"page-title\">Account Settings</h1><p class=\"card-description text-muted\">Manage your account settings and security.</p><div class=\"grid grid-cols-1 md:grid-cols-2 gap-6\"><!-- Change Password Card --><div class=\"card\"><div class=\"card-body\"><h3 class=\"card-title\">Change Password</h3><p class=\"card-description text-muted\">Use this form to change your login password.</p><form hx-put=\"/ui-api/account/password\" hx-target=\"#password-result\" hx-swap=\"innerHTML\" class=\"margin-top-4\"><div class=\"form-group\"><label for=\"current-password\" class=\"form-label\">Current Password</label> <input id=\"current-password\" name=\"current-password\" type=\"password\" required class=\"form-input\" placeholder=\"Enter your current password\"><p class=\"text-muted text-sm mt-1\">We need your current password to verify your identity.</p></div><div class=\"form-group\"><label for=\"new-password\" class=\"form-label\">New Password</label> <input id=\"new-password\" name=\"new-password\" type=\"password\" required minlength=\"11\" class=\"form-input\" placeholder=\"Enter your new password (minimum 11 characters)\"><p class=\"text-muted text-sm mt-1\">Password must be at least 11 characters long.</p></div><div class=\"form-group\"><label for=\"confirm-password\" class=\"form-label\">Confirm New Password</label> <input id=\"confirm-password\" name=\"confirm-password\" type=\"password\" required minlength=\"11\" class=\"form-input\" placeholder=\"Confirm your new password\"></div><div class=\"form-group\"><button type=\"submit\" class=\"btn btn-primary\">Update Password</button></div></form></div></div></div><div id=\"password-result\"><!-- Results will appear here --></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = BaseLayout("Account Settings").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
