name: CD

on:
  push:
    branches: [cd]

jobs:
  tests:
    name: Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"
          cache: true                                
          cache-dependency-path: app/go.sum    

      - name: Download Go modules
        run: go mod download

      - name: Build app
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build ./cmd/signalsd/

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push docker image
        run: |
          cd ..
          gcloud builds  submit  --config=cloudbuild.yaml . --async


